### ISSUE TITLE
Page expired

### ISSUE THREAD

**Issue by dimovdaniel** [dacoto/laravel-wizard-installer#17]
https://github.com/dacoto/laravel-dashboard-installer/blob/ad34f223e5fc0e3a036d77a6328609fe15b33dbf/src/Controllers/InstallDatabaseController.php#L69

When you do that ($request->all()), the _token is also passed. 
Thus, next time you call that action, old _token is used, resulting in 419 error

**Comment by dacoto97** [comment]
Hello, thank you very much for your report. We will try to update the script to fix this bug.

**Comment by dacoto97** [comment]
It is fixed in the next release.
