### ISSUE TITLE
APP_KEY is not set

### ISSUE THREAD

**Issue by dimovdaniel** [dacoto/laravel-wizard-installer#18]
https://github.com/dacoto/laravel-dashboard-installer/blob/ad34f223e5fc0e3a036d77a6328609fe15b33dbf/src/Controllers/InstallKeysController.php#L51

Should be 
```
EnvEditor::setEnv('APP_KEY', trim(str_replace('"', '', Artisan::output())));
```

**Comment by dacoto97** [comment]
Hello, thank you very much for your work, if you could do the PR with the modification, we would be very grateful!
If you can't, it will take a few weeks to incorporate this modification.

**Comment by dacoto97** [comment]
It is fixed in the next release.
